### ISSUE TITLE
Simple example throws ProtocolError

### ISSUE THREAD

**Issue by jenschelkopf** [grasshoppergroup/adhearsion-cpa#1]
I'm running into an issue using Adhearsion-CPA.  When I call detect_tone I get a ProtocolError.  This smells like a version problem, but I'm using the versions specified in the Adhearsion-CPA readme.

My call controller is nearly identical to the example in Adhearsion-CPA's readme:

<pre>
def run
  answer
  tone = detect_tone(:fax, timeout: 5)
  if tone
    logger.info "Good job! You sound just like a #{tone.type}"
  else
    logger.info "Nope, you didn't make a convincing enough beep"
  end
end
</pre>

I'm pretty sure that I'm using the right gem versions:

<pre>
> less Gemfile
gem 'adhearsion', '~> 2.4'
gem 'adhearsion-asr'
gem 'punchblock', github: "adhearsion/punchblock", branch: "feature/cpa_fax"
gem 'adhearsion_cpa', path: '/root/adhearsion-cpa'
</pre>

<pre>
> bundle show
  * adhearsion (2.4.0)
  * adhearsion_cpa (0.0.1 be71070)
  * punchblock (2.0.2 a6cfef3)
</pre>

I'm using Freeswitch v1.2.stable + mod_rayo.

I'm thinking maybe the version of mod_rayo that I'm using doesn't support cpa, but I don't see any versioning information in its [documentation](https://wiki.freeswitch.org/wiki/Mod_rayo) or in the Adhearsion-CPA readme.  I could use some help figuring out what I did wrong in my setup, or avenues to investigate.

Adhearsion stack trace is [here](http://pastebin.com/cE97Xxar).
Freeswitch log is [here](http://pastebin.com/WFw0Zc92).

**Comment by JustinAiken** [comment]
@crienzo hasn't quite finished adding CPA to mod_rayo yet, this gem's a bit a head...

**Comment by benlangfeld** [comment]
@justinaiken or @crienzo are the best people to answer this :)

**Comment by JustinAiken** [comment]
Okay @jrullmann, now this gem should be actually usable :) 

Grab the latest Freeswitch install from source you can (cpa support is very new), and this gem... 

Sorry you tried it out when I was writing it to match the spec before anything actually existed, but now all the pieces should be in place.
